"""
Output file writing utilities
"""
import os
from typing import List
from datetime import datetime


def write_summaries_to_file(summaries: List[str], output_file: str = 'codectx.md') -> None:
    """
    Write summaries to output file with timestamps.
    
    Args:
        summaries: List of summary strings (should include timestamps)
        output_file: Output file path (default: 'codectx.md')
    """
    if not summaries:
        return
    
    # Create header with metadata
    header = f"""# Project Summary

Generated by codectx on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

Total files processed: {len(summaries)}

---

"""
    
    try:
        with open(output_file, 'w', encoding='utf-8') as file:
            file.write(header)
            for summary in summaries:
                file.write(summary)
                if not summary.endswith('\n'):
                    file.write('\n')
                file.write('\n')  # Extra newline between summaries
    except Exception as e:
        raise IOError(f"Failed to write to {output_file}: {e}")


def format_file_summary(file_path: str, content: str, summary_date: datetime = None) -> str:
    """
    Format a file summary with timestamp metadata.
    
    Args:
        file_path: Path to the file
        content: Summary content
        summary_date: Date when summary was created (defaults to now)
        
    Returns:
        Formatted summary string with timestamp
    """
    if summary_date is None:
        summary_date = datetime.now()
    
    timestamp_str = summary_date.strftime('%Y-%m-%d %H:%M:%S')
    
    return f"""## {file_path}

Summarized on {timestamp_str}

{content}"""